base_homepage:
    path:     /base/index
    defaults: { _controller: baseBundle:Default:index }

base_blog:
    path:     /base/blog
    defaults: { _controller: baseBundle:Default:blog }

base_about:
    path:     /base/about
    defaults: { _controller: baseBundle:Default:about }

base_cart:
    path:     /base/cart
    defaults: { _controller: baseBundle:Default:cart }

base_checkout:
    path:     /base/checkout
    defaults: { _controller: baseBundle:Default:checkout }

base_contact:
    path:     /base/contact
    defaults: { _controller: baseBundle:Default:contact }

base_portfolio:
    path:     /base/portfolio
    defaults: { _controller: baseBundle:Default:portfolio }

base_shop:
    path:     /base/shop
    defaults: { _controller: baseBundle:Default:shop }

base_shop_details:
    path:     /base/shop_details
    defaults: { _controller: baseBundle:Default:shop_details}

base_portfolio_details:
    path:     /base/portfolio_details
    defaults: { _controller: baseBundle:Default:portfolio_details}

base_blog_details:
    path:     /base/blog_details
    defaults: { _controller: baseBundle:Default:blog_details}

base_event:
    path:     /base/event
    defaults: { _controller: baseBundle:Default:event}
base_forming:
    path:     /base/forming
    defaults: { _controller: baseBundle:Default:forming}

base_login:
    path:     /base/login
    defaults: { _controller: baseBundle:Default:login}

admin_404:
    path:     /admin/404
    defaults: { _controller: baseBundle:Admin:a404}

admin_blank:
    path:     /admin/blank
    defaults: { _controller: baseBundle:Admin:blank}

admin_charts:
    path:     /admin/charts
    defaults: { _controller: baseBundle:Admin:charts}

admin_pass:
    path:     /admin/pass
    defaults: { _controller: baseBundle:Admin:pass}

admin_index:
    path:     /admin/index
    defaults: { _controller: baseBundle:Admin:index}

admin_login:
    path:     /admin/login
    defaults: { _controller: baseBundle:Admin:login}

admin_register:
    path:     /admin/register
    defaults: { _controller: baseBundle:Admin:register}

admin_tables:
    path:     /admin/tables
    defaults: { _controller: baseBundle:Admin:tables}
#----------------------  LIVRAISON   ----------------------

admin_livreur:
    path:     /admin/livreur
    defaults: { _controller: baseBundle:Livreur:livreur}

admin_listeLivreur:
    path:     /admin/listeLivreur
    defaults: { _controller: baseBundle:Livreur:listeLivreur}

admin_supprimerLivreur:
    path:     /admin/supprimerLivreur
    defaults: { _controller: baseBundle:Livreur:supprimerLivreur}

admin_deleteLivreur:
    path:     /admin/deleteLivreur/{id}
    defaults: { _controller: baseBundle:Livreur:deleteLivreur}

admin_modifierLivreur:
    path:     /admin/modifierLivreur
    defaults: { _controller: baseBundle:Livreur:modifierLivreur}

admin_ajouterDispo:
    path:     /admin/ajouterDispo
    defaults: { _controller: baseBundle:Livreur:ajouterDispo}

admin_suppDispo:
    path:     /admin/suppDispo
    defaults: { _controller: baseBundle:Livreur:suppDispo}

admin_map:
    path:     /admin/map
    defaults: { _controller: baseBundle:Livreur:map}

admin_ajouterLivraison:
    path:     /admin/ajouterLiv
    defaults: { _controller: baseBundle:Livreur:ajouterLiv}


#----------------------------------------------------------

show_event:
    path:     /admin/show_event
    defaults: { _controller: baseBundle:Event:show }

add_event:
    path:     /admin/add_event
    defaults: { _controller: baseBundle:Event:add }

delete_event:
    path:     /admin/delete/{id}
    defaults: { _controller: baseBundle:Event:delete }

change_event:
    path:     /admin/change/{id}
    defaults: { _controller: baseBundle:Event:change }

show_stand:
    path:     /admin/stand
    defaults: { _controller: baseBundle:Event:stand }

add_stand:
    path:     /admin/add_stand
    defaults: { _controller: baseBundle:Event:standaj }

rent_stand:
    path:     /base/rentStand/{idEvent}
    defaults: { _controller: baseBundle:Event:rentStand }

show_par:
    path:     /admin/par
    defaults: { _controller: baseBundle:Event:par }

formateur_afficherformateur:
    path:     /afficher
    defaults: { _controller: baseBundle:Formation:view }
formation_ajoutformateur:
        path:     /ajout
        defaults: { _controller: baseBundle:Formation:create }
supp_formateur:
    path: /supprimer/{id}
    defaults: { _controller: baseBundle:Formation:supprimer }
modif_formateur:
    path: /modifier/{id}
    defaults: { _controller: baseBundle:Formation:modifier }
afficherformation:
    path:     /afficherf
    defaults: { _controller: baseBundle:Formation:afficherFormation }
ajoutformation:
    path:     /ajoutf
    defaults: { _controller: baseBundle:Formation:createf }
supp_formation:
    path: /supprimerf/{id}
    defaults: { _controller: baseBundle:Formation:supprimerf }
modif_formation:
    path: /modifierf/{id}
    defaults: { _controller: baseBundle:Formation:modifierf }

test:
    path: /test
    defaults: { _controller: baseBundle:Event:test }




