livraison_homepage:
    path:     /livraison
    defaults: { _controller: livraisonBundle:Default:index }

livreur_login:
    path:     /livraison/login
    defaults: { _controller: livraisonBundle:livreur:login }

livreur_index:
    path:     /livraison/index
    defaults: { _controller: livraisonBundle:livreur:index }

