<?php

namespace baseBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livreurRepository extends \Doctrine\ORM\EntityRepository
{
}
