<?php

namespace baseBundle\Repository;

/**
 * MaterielsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielsRepository extends \Doctrine\ORM\EntityRepository
{
}
